Feature/issue 529
AtlasOfLivingAustralia/volunteer-portal pull request #546
Opened 2022-09-29 06:18 UTC by cdausmus

Added enabled property for email notifications. Added check for this new property when activating and completing an expedition. Only send email notification if this property is set to true.

Tested and confirmed by Ciaran Mathewson.

2022-10-11 06:31 UTC, temi commented on grails-app/controllers/au/org/ala/volunteer/ProjectController.groovy
> +            def isNotifyEnabled = (true == grailsApplication.config.notifications.project.enabled)
It is possible `notifications.project.enabled` is a string boolean value if the configuration is set in properties file. This code might not work then. Similar comments below.

2022-10-11 06:33 UTC, temi requested changes
One comment.

2022-10-12 01:39 UTC, cdausmus commented
Updated, tested with 'true', 'false' and true, false.

2022-10-23 23:07 UTC, temi approved these changes

2022-10-24 03:39 UTC, merged